### PR TITLE
Force out of source builds

### LINKED ISSUE #10: Handle packages which don't support out of source builds
Right now we just make them build within the source directory but with #6 they will fail.

Instead:
* Assume by default packages support out of source builds and respect `$cur__target_dir`. Again #6 will catch the violations here.
* Make an opt-out mechanism for packages which *doesn't* support out of source builds.
* For packages which don't support out of source build we need to copy its sources over to `$cur__target_dir` on each build.

### PR DESCRIPTION
**Pull request by andreypopp**
- [x] Land #17 first
- [x] More testing needed
- [x] Regenerate `@opam/*` packages so that the have `"buildOutOfSource": false`
- [x] Update OCaml compiler with `"buildOutOfSource": false`.

Opening it so that we track the work in progress.

Fixes #10 

If `esy.buildOutOfSource` key in `package.json` is `false` (if not present it is assumed to be `true`) then copy sources to `$cur__target_dir`, also set `$cur__root` to be `$cur__target_dir`.

Also modify sandbox config to prevent messing with source directory.

### CODE REVIEW

File: lib/Sandbox.js [hunk 1]
```diff
@@ -59,6 +59,14 @@ export type EnvironmentVarExport = {
   __BUILT_IN_DO_NOT_USE_OR_YOU_WILL_BE_PIPd?: boolean;
 };
 
+export type EsyConfig = {
+  build: ?string;
+  buildOutOfSource: boolean;
```
Comment (andreypopp) [inline lib/Sandbox.js]: New `"esy.buildOutOfSource" key here. Indicates if a package can build itself out of source directory. If key isn't present — then it is assumed to be `true`. If key is present and set to `false` then we copy `$cur__root` into `$cur__target_dir` before the build.

File: lib/PackageEnvironment.js [hunk 2]
```diff
@@ -184,14 +184,19 @@ function builtInsPerPackage(
...
+      version || null
     ),
-    [`${prefix}__root`]: builtIn(
+    [`${prefix}__source_root`]: builtIn(
       relativeToSandbox(sandbox.packageInfo.rootDirectory, rootDirectory)
     ),
+    [`${prefix}__root`]: builtIn(
+      esy.buildOutOfSource
+        ? relativeToSandbox(sandbox.packageInfo.rootDirectory, rootDirectory)
+        : targetPath(sandbox, packageInfo, '_build')
```
Comment (andreypopp) [inline lib/PackageEnvironment.js]: If package can't build out of source then we copy sources over to `$cur__target_dir` and set `$cur__root` to be equal to `$cur__target_dir`.

File: lib/PackageEnvironment.js [hunk 3]
```diff
@@ -184,14 +184,19 @@ function builtInsPerPackage(
...
     [`${prefix}__name`]: builtIn(
-      packageJson.name
+      name
     ),
     [`${prefix}__version`]: builtIn(
-      packageJson.version || null
+      version || null
     ),
-    [`${prefix}__root`]: builtIn(
+    [`${prefix}__source_root`]: builtIn(
```
Comment (andreypopp) [inline lib/PackageEnvironment.js:192]: New env var here — `$*__source_root` — the real source root, even when package can't be built out of source.

File: lib/esyBuildEjectCommand.js [hunk 4]
```diff
@@ -219,29 +235,41 @@ function buildEjectCommand(
 
           (allow file-write*
             (literal "/dev/null")
-            (subpath "$(realpath /private/tmp)")
+            (subpath "$(realpath /tmp)")
             (subpath "$(realpath $(TMPDIR))")
-            ; TODO: Make sure we remove it when we have proper out of source builds
-            (subpath "$(realpath ${packageInfo.rootDirectory})")
```
Comment (andreypopp) [inline lib/esyBuildEjectCommand.js:225]: That validates packages can write into their own source directories.

**Review by andreypopp — COMMENTED** [review]
Ready to be merged. Tested with esy-ocaml-project on macOS and Linux.

**Comment by andreypopp** [comment]
Found a bug with a root package having `"buildOutOfSource": false`.

File: lib/Sandbox.js (hunk 1 above)
Comment (jordwalke) [reply lib/Sandbox.js]: I tend to prefer these "presence" booleans to be such that absent implies `false`. So in that case, it would probably be named something like `buildsInSource`. Thoughts?

File: lib/esyBuildEjectCommand.js [hunk 5]
```diff
@@ -239,8 +240,10 @@ function buildEjectCommand(
           type: 'rule',
           target: packageRoot,
           command: withPackageEnv(outdent`
-            rm -rf $cur__root; \\
-            cp -r $cur__source_root $cur__root
+            if [ ! -d "$cur__install" ]; then \\
+              rm -rf $cur__root; \\
+              rsync --quiet --archive $cur__source_root/ $cur__root --exclude $cur__root; \\
```
Comment (andreypopp) [inline lib/esyBuildEjectCommand.js:245]: We exclude `$cur__root` here because in case of the root package — we don't rsync `_build` into itself.

File: lib/Sandbox.js (hunk 1 above)
Comment (andreypopp) [reply lib/Sandbox.js]: Agreed, defaulting to `false` is more intuitive. Though `buildsInSource` name is not prone to typos — I'd write `buildInSource` most of the times. Which is by the way reminds me that we probably need `package.json` config validation in esy.

Comment (jordwalke) [reply lib/Sandbox.js]: I think either is prone to typos `buildOutOfSource`/`buildsOutOfSource`.

Comment (andreypopp) [reply lib/Sandbox.js]: Yes, just that `buildOutOfSource` aligns nicely with `build`.

Comment (andreypopp) [reply lib/Sandbox.js]: Ok, fixed that to `buildsInSource` being `false` by default. Test pass.

File: lib/PackageEnvironment.js (hunk 3 above)
Comment (jordwalke) [reply lib/PackageEnvironment.js:192]: Can you PR to PJC spec once landed?

**Comment by jordwalke** [comment]
Spectacular!!
